### ISSUE TITLE
Non-interactive and interactive versions of verdi setup do not use same code

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1483]
Especially the code that validates the user input is not shared by these two pathways. The validation should be abstracted and used by both versions of the command

**Comment by sphuber** [comment]
Fixed in #1795

**Comment by giovannipizzi** [comment]
Actually this was not fully fixed... 
verdi setup still uses (in the interactive mode) an old, non-click-compliant code (with handwritten interactivity, questions, readline use etc.) which by the way is also different from the non-interactive branch of the code. It even still has questions for mysql, sqlite, ...
We should remove the old, interactive code and unify with the non-interactive one (this might also fix some of the other issues (maybe #899?)
